wandb_version: 1

model_name:
  desc: null
  value: Alibaba-NLP/gte-multilingual-base
audio_encoder:
  desc: null
  value: jonatasgrosman/wav2vec2-large-xlsr-53-english
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 30
d_fuse:
  desc: null
  value: 256
pooling_dropout:
  desc: null
  value: 0.3
regression_dropout:
  desc: null
  value: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.46.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1752430469.697266
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 105
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.8.17
      5: 0.16.2
      6: 4.46.3
      8:
      - 2
      - 5
      13: linux-x86_64
